### ISSUE TITLE
Http error 409 is not processed

### ISSUE THREAD

**Issue by n-elloco** [contentful/contentful-management.py#2]
In case when I try to update old entry (or asset) instance the Contentful raises exception VersionMismatch (HTTP 409), but in the contentful-management.py this error is not processed. Moreover, we have a bug when this tool try to process the error

```
Error
Traceback (most recent call last):
  
    asset.publish()
  File ".../lib/python3.6/site-packages/contentful_management/resource.py", line 326, in publish
    headers=self._update_headers()
  File ".../lib/python3.6/site-packages/contentful_management/client.py", line 475, in _put
    return self._request('put', url, attributes, **kwargs)
  File ".../lib/python3.6/site-packages/contentful_management/client.py", line 441, in _request
    error = get_error(response)
  File ".../lib/python3.6/site-packages/contentful_management/errors.py", line 91, in get_error
    return error_class(response)
  File ".../lib/python3.6/site-packages/contentful_management/errors.py", line 20, in __init__
    super(HTTPError, self).__init__(response.json()['message'])
KeyError: 'message'
```

**Comment by dlitvakb** [comment]
Hey @n-elloco,

Looks like a bug indeed! I'll look into it and fix it as soon as possible.

Cheers

**Comment by elanid** [comment]
I seem to be having a similar problem when I go to publish an entry I've just added. I'm using python2 -- is it possible that your fix only went to the py3 codebase?

```
new_entry.publish()
File "/Users/rs/cornell/contentful-events/events-copypasta/env/lib/python2.7/site-packages/contentful_management/resource.py", line 340, in publish
headers=self._update_headers()
File "/Users/rs/cornell/contentful-events/events-copypasta/env/lib/python2.7/site-packages/contentful_management/client.py", line 538, in _put
return self._request('put', url, attributes, **kwargs)
File "/Users/rs/cornell/contentful-events/events-copypasta/env/lib/python2.7/site-packages/contentful_management/client.py", line 504, in _request
error = get_error(response)
File "/Users/rs/cornell/contentful-events/events-copypasta/env/lib/python2.7/site-packages/contentful_management/errors.py", line 107, in get_error
return error_class(response)
File "/Users/rs/cornell/contentful-events/events-copypasta/env/lib/python2.7/site-packages/contentful_management/errors.py", line 20, in __init__
super(HTTPError, self).__init__(response.json()['message'])
```

**Comment by dlitvakb** [comment]
Hey @elanid,

Looks like you're running an older version of the gem. Please update and let me know if that helps.

Cheers

**Comment by elanid** [comment]
Hey @dlitvakb,

I believe per pip that I've updated to the current version (contentful-management-1.5.1), but I'm still seeing a very intermittent problem with this publish call:

File "/Users/rs/cornell/contentful-events/events-copypasta/build_contentful_data.py", line 131, in send_to_contentful
    new_entry.publish()
File "/Users/rs/cornell/contentful-events/events-copypasta/env/lib/python2.7/site-packages/contentful_management/resource.py", line 373, in publish
    headers=self._update_headers()
File "/Users/rs/cornell/contentful-events/events-copypasta/env/lib/python2.7/site-packages/contentful_management/client.py", line 714, in _put
    return self._request('put', url, attributes, **kwargs)
File "/Users/rs/cornell/contentful-events/events-copypasta/env/lib/python2.7/site-packages/contentful_management/client.py", line 682, in _request
    raise error
ServerError: HTTP status code: 500
Message: Internal server error.
Request ID: 635f02eec18852700f9fb258641e201c

The lowest level of the call looks a little different, but if I run this same code with the earlier version of the package (contentful-management 1.3.1), then I do get the same error we were discussing previously. Do you have any suggestions?

**Comment by dlitvakb** [comment]
Hey @elanid,

This 500 error seems to be a very different error and related to the Contentful service itself and not to this package.

Can you open a support request in https://support.contentful.com and include the Request ID you posted here?

This will help our support staff to understand what may be going on, as it looks like a server error.

Cheers

**Comment by dlitvakb** [comment]
Hey @elanid,

The error you're finding previous to the update is unrelated, and you're seeing it because the old version had wrong assumptions about the responses that came from the API on some of the possible errors.

New error you're getting is no longer due to an SDK bug and 100% due to a server error.

Please create a support request on https://support.contentful.com and they'll be able to help you further.

Please include the Request ID present in the error information you sent me before.

Cheers

**Comment by elanid** [comment]
Thanks, I appreciate the further clarification. I've submitted a support request.
